; Script generated by Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ModScan Pro"
#define MyAppVersion "1.0"
#define MyAppPublisher "2EDGE Technology Co.,Ltd"
#define MyAppURL "https://www.2edge.co.th"
#define MyAppExeName "server.js"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside Inno Setup)
AppId={{A1B2C3D4-E5F6-7890-1234-567890ABCDEF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={commonpf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=admin
OutputDir=installer_output
OutputBaseFilename=ModScanPro_Setup_v1.0
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; Copy the entire distributed folder
Source: "..\dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: We assume 'nssm.exe' is placed in the 'dist' folder or scripts folder. 
; If you want to bundle nssm, force the user to provide it.
Source: "..\scripts\nssm.exe"; DestDir: "{app}"; Flags: ignoreversion; Check: FileExists('..\scripts\nssm.exe')

[Icons]
Name: "{group}\{#MyAppName} Web Interface"; Filename: "http://localhost:3000"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"

[Run]
; 1. Install Dependencies (Optional - assumes Node is in PATH)
Filename: "cmd.exe"; Parameters: "/c npm install --production --no-save"; WorkingDir: "{app}"; Flags: runhidden; StatusMsg: "Installing dependencies..."

; 2. Install Service using NSSM (Bundled or Assumed)
; We try to use the bundled nssm.exe if it exists, otherwise we hope it's in PATH
Filename: "{app}\nssm.exe"; Parameters: "install ModScanPro ""{cmd}"" ""/c node {app}\server.js"""; Flags: runhidden; StatusMsg: "Registering Service..."; Check: FileExists(ExpandConstant('{app}\nssm.exe'))
Filename: "{app}\nssm.exe"; Parameters: "set ModScanPro AppDirectory ""{app}"""; Flags: runhidden; Check: FileExists(ExpandConstant('{app}\nssm.exe'))
Filename: "{app}\nssm.exe"; Parameters: "start ModScanPro"; Flags: runhidden; StatusMsg: "Starting Service..."; Check: FileExists(ExpandConstant('{app}\nssm.exe'))

; Fallback: If nssm is not bundled, verify node check? 
; For a professional installer, you SHOULD bundle nssm.exe in the source folder.

[UninstallRun]
; Stop and Remove Service
Filename: "{app}\nssm.exe"; Parameters: "stop ModScanPro"; Flags: runhidden; RunOnceId: "StopService"
Filename: "{app}\nssm.exe"; Parameters: "remove ModScanPro confirm"; Flags: runhidden; RunOnceId: "RemoveService"

[Code]
// Helper function to check if Node.js is installed
function InitializeSetup(): Boolean;
var
  ErrorCode: Integer;
begin
  if not ShellExec('', 'node', '-v', '', SW_HIDE, ewWaitUntilTerminated, ErrorCode) then
  begin
    MsgBox('Node.js is required but not found.' + #13#10 + 'Please install Node.js (LTS) before installing this application.', mbCriticalError, MB_OK);
    Result := False;
  end
  else
  begin
    Result := True;
  end;
end;
